Import('high_opt_env')

sources = Split("""cholesky_timing.cpp
             matrix_product_timing.cpp
             rec_matrix_product_timing.cpp
	     empty.cpp
""")

programs = []
for p in sources:
    programs.append(high_opt_env.Program(p))


p = high_opt_env.Program(Split('no_inline_timing.cpp no_inline_ext.cpp'))
programs.append(p)

Default(high_opt_env.Program('empty.cpp'))

# need target everything or something like that
