INCLUDE_DIRS = -I${MTL_MORTON_BOOST_ROOT} -I${MTL_BOOST_ROOT} -I${BOOST_ROOT}

CXXFLAGS = ${INCLUDE_DIRS} -Wno-long-double  -DMTL_USE_NEW_RECURATOR -g
#CXXFLAGS += -DNDEBUG -O2

all: morton_dense matrix_product


#morton_dense:	morton_dense.cpp
#	g++ morton_dense.cpp -o morton_dense ${CXX_FLAGS}

clean:
	rm morton_dense matrix_product *~



