factorial: factorial.cpp apply.hpp assign.hpp begin.hpp constant.hpp env.hpp if.hpp lambda.hpp let.hpp set.hpp tags.hpp var.hpp while.hpp
	icc -I/u/jewillco/boost -O3 -o factorial factorial.cpp
	icc -I/u/jewillco/boost -O3 -S factorial.cpp
