// $COPYRIGHT$

#ifndef MTL_FILL_INCLUDE
#define MTL_FILL_INCLUDE

#include <algorithm>

namespace mtl {

// Sets all values of a matrix
template <class Matrix>
void fill(Matrix& ma, typename Matrix::value_type value)
{
    std::fill(ma.elements(), ma.elements()+ma.num_elements(), value);
}

// Temporary solution
// will be replaced by sequences and cursors generated by begin<all>(ma) and end<all>(ma)
// Using segmented cursors, matrices with non-contigous element storing can be handled

} // namespace mtl

#endif // MTL_FILL_INCLUDE
