#!/bin/bash

CC="gcc"
CXX="g++"
#CC="icc"
#CXX="icc"

#-fkeep-inline-functions 

# flags for g++
# problems with -static on MacOS ...
FLAGS="-O3 -finline-limit=2000 -Winline -I/usr/include/malloc -dynamic"

# flags for icc
#FLAGS="-O3 -ipo -no-prec-div -static -ip -xN"

$CC -c $FLAGS iohb.c;
$CXX -c $FLAGS bounds.cpp;
$CXX -c $FLAGS matrix.cpp;
$CXX -c $FLAGS iLU.cpp;
$CXX -c $FLAGS iUL.cpp;
$CXX -c $FLAGS sysSolve.cpp;

$CXX -o mk_spdMat mk_spdMat.cpp $FLAGS;
$CXX -o mkInput mkInput.cpp iohb.o $FLAGS;

$CXX -o sysSolver sysSolver.cpp  \
	iohb.o bounds.o matrix.o iLU.o iUL.o sysSolve.o \
	$FLAGS;




