#!/bin/bash -x 

make -C ~/projekte/topomap/MPIParMETIS 
make -C ~/projekte/topomap 

#BOOST_HOME=$HOME/bgl-soft
BOOST_HOME=/opt/boost_1_38/
#BOOST_SUFFIX=-mt
BOOST_SUFFIX=-gcc43-mt-1_38

#mpicxx mpi_3_topology_test.cpp -DMTL_HAS_PARMETIS -DMTL_HAS_TOPOMAP \
mpicxx mpi_3_parmetis_matrix_migration_test.cpp -DMTL_HAS_PARMETIS -DMTL_HAS_TOPOMAP \
  -o metis -DMTL_HAS_MPI -I../../../.. \
  -I$HOME/projekte/topomap/MPIParMETIS/ParMetis-3.1.1 \
  -I$HOME/projekte/topomap/MPIParMETIS/ \
  -I$HOME/projekte/topomap/ \
  -I$BOOST_HOME/include/boost-1_38 \
  -L$BOOST_HOME/lib -lboost_mpi$BOOST_SUFFIX -lboost_serialization$BOOST_SUFFIX \
  $HOME/projekte/topomap/MPIParMETIS/libmpiparmetis.a \
  $HOME/projekte/topomap/libtopomap.a \
  $HOME/projekte/topomap/virt_graph_scal.o \
  $HOME/projekte/topomap/MPIParMETIS/ParMetis-3.1.1/libparmetis.a \
  $HOME/projekte/topomap/MPIParMETIS/ParMetis-3.1.1/libmetis.a 
