Import('opt_env check')

sources = Split("""cg_test.cpp
	           bicg_test.cpp
""")


programs = []
for p in sources:
    programs.append(opt_env.Program(p))

if int(check):
    for p in programs:
        opt_env.AddPostAction(p, p[0].abspath)

Default(programs)
