Import('debug_env')

sources = Split("""base_case_conversion.cpp
             bit_masking.cpp
             cholesky_test.cpp
             complexity.cpp
             compressed2D.cpp
             compressed2D_inserter.cpp
             dense2D.cpp
             dilated_int.cpp
             matrix_product_test.cpp
             morton_dense.cpp
             sub_matrix.cpp
	     print_matrix_test.cpp
	     set_to_zero_test.cpp
""")

programs = []
for p in sources:
    programs.append(debug_env.Program(p))

Default(programs)
