Import('opt_env check')

sources = Split("""vector1.cpp
                   vector2.cpp
                   vector_norm.cpp
                   vector_reduction.cpp
""")


programs = []
for p in sources:
    programs.append(opt_env.Program(p))

if int(check):
    for p in programs:
        opt_env.AddPostAction(p, p[0].abspath)

Default(programs)
