Import('opt_env check')
import glob

sources = glob.glob("*.cpp")

if opt_env['CC'] == 'cl':
    # assignment doesn't work with templates on cl
    sources.remove('vector2.cpp')

programs = []
for p in sources:
    programs.append(opt_env.Program(p))

if int(check):
    for p in programs:
        opt_env.AddPostAction(p, p[0].abspath)

Default(programs)
