Import('opt_env check')

sources = Split("""vector1.cpp
                   vector2.cpp
                   vector_norm.cpp
                   vector_reduction.cpp
                   dot.cpp
                   vector_expr.cpp
                   rich_vector_expr.cpp
                   dense2D.cpp
                   morton_dense.cpp
                   compressed2D.cpp
                   matrix_mult_simple.cpp
                   matrix_operations.cpp
                   insert.cpp
                   element_matrix.cpp
                   matrix_norms.cpp
                   matrix_functions.cpp
""")


programs = []
for p in sources:
    programs.append(opt_env.Program(p))

if int(check):
    for p in programs:
        opt_env.AddPostAction(p, p[0].abspath)

Default(programs)
