import glob, re

Import('debug_env mpi_debug_env check')

sources = glob.glob("*.cpp")

# Have to work on this
# sources.remove('mpi_2_ilu_0_bicg_test.cpp')


programs, mpi_programs = [], []
for p in sources:
    if 'mpi_' == p[0:4]:
        mpi_programs.append(mpi_debug_env.Program(p))
    else:
        programs.append(debug_env.Program(p))

if int(check):
    for p in programs:
        debug_env.AddPostAction(p, p[0].abspath)
    for p in mpi_programs:
        tmatch = re.search('mpi_(\d*).*', str(p))
        mpi_debug_env.AddPostAction(p, 'mpirun -mca btl tcp,self -np ' + tmatch.group(1) + ' ' + p[0].abspath)

Default(programs + mpi_programs)
