#!/usr/bin/env python

import sys, getopt, re, os

if len(sys.argv) < 2:
  print "syntax:", sys.argv[0], "program_name .."
  sys.exit(1)

tmatch = re.search('mpi_(\d*).*', sys.argv[1])
if not tmatch and len(sys.argv) > 2:
  tmatch = re.search('mpi_(\d*).*', sys.argv[2])
if not tmatch:
  print "Program name must start with mpi_nnn where nnn is the number of processes."
  sys.exit(1)

command= "mpirun -mca btl tcp,self -np " + tmatch.group(1) + " " + " ".join(sys.argv[1:])	
#print command
os.system(command)
