import os

Import('debug_env check')

sources = Split("""
		simple_test2.cpp 
		simple_test.cpp 
		positive_real.cpp	
		positive_real_explicit.cpp 
		positive_real_power.cpp 
		positive_real_power_explicit.cpp 
		string_example.cpp
		float_example.cpp 
		int_example.cpp 
		mod_n_example.cpp 
		mod_n_power.cpp 
		accumulation_example.cpp
		concept_map_test.cpp      
		int_example.cpp  
		accumulation_measuring.cpp
""")

# For testing only
# sources = ["simple_test.cpp"]

concept_env = debug_env.Copy()

# Check if conceptg++ is in path (return code != 0)
# Turn off for now
if 1: # os.system('conceptg++ -v'):
    sources = []
else:
    # TBD: check whether options are okay
    concept_env['ENV']['PATH'] = os.environ['PATH']
    concept_env['CXX'] = 'conceptg++'

programs = []
for p in sources:
    programs.append(concept_env.Program(p))

if int(check):
    for p in programs:
        concept_env.AddPostAction(p, p[0].abspath)

Default(programs)
