import glob

Import('high_opt_env check')

sources = glob.glob("*.cpp")


programs = []
for p in sources:
    programs.append(high_opt_env.Program(p))

if int(check):
    for p in programs:
        high_opt_env.AddPostAction(p, p[0].abspath)

Default(programs)
