Import('debug_env')

list = Split("""iterator_adapter.cpp unroll.cpp unroll_rec.cpp 
   mat_vec_mult_timing.cpp unroll_matrix_mult.cpp insertion_timing.cpp empty.cpp""")

for program in list:
    debug_env.Program(program)

Default('empty')
