CXXFLAGS += -I${BOOST_ROOT} -I${MTL_BOOST_ROOT} -I${GLAS_ROOT} 

CXX = conceptg++

it:	all

all:	age_example1

age_example1:	age_example1.cpp 

concepts_hpp:	${MTL_BOOST_ROOT}/boost/numeric/mtl/scalar/concepts.hpp